### PR TITLE
OCPCLOUD-2297: webhook/openstack: validate etcd block device size

### PR DESCRIPTION
**Pull request by EmilienM**
webhook/openstack: add validation for etcd block device size

### CODE REVIEW

**Comment by EmilienM** [comment]
/hold
the vendoring patch is using a fork for testing purpose but I'll change it at some point when the dependent PR has merged.

**Review by JoelSpeed — COMMENTED** [review]
/approve
/lgtm

**Comment by EmilienM** [comment]
@JoelSpeed it sounds like I need `acknowledge-critical-fixes-only` label. Is it something possible on your side? Let me know if you need anything from me.

**Pull request merged**
