### PR TITLE
OCPBUGS-22864: Revert "Revert #239 "OCPCLOUD-2167: Test unhealthy node cases""

### PR DESCRIPTION
**Pull request by odvarkadaniel**
Reverts openshift/cluster-control-plane-machine-set-operator#262

Want to investigate possible timeouts or flakes that might occur with the newly introduced test cases.

### CODE REVIEW

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 15

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp 15

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp 15

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 15

**Comment by odvarkadaniel** [comment]
From what I have seen, the main issue is that when dealing with "broken" nodes/machines, the cloud provider or OC itself can be rather slow, so we encounter really long times for a new node and machine to come up. Afterwards, we need for the cluster to stabilise, which can take up to 90 minutes from what I have seen (usually around 60-90 minutes for the timeout in `ItShouldReplaceTheOutDatedMachineInDeleting` function).

From the last stretch testing of the `e2e-periodics`, we can see that on AWS, the `e2e-periodics` passed 14/15 times. For GCP, out of 15 runs, the installation failed once, once it failed to increase the type instance of machines and twice it failed on the newly introduced test, other 11 runs passed. This is a pretty significant improvement and should be considered as good enough in my opinion.

I will also make sure that the test `e2e-openstack-operator-zone` passes, which seems to encounter similar issues.

**Comment by damdo** [comment]
Do we know why we had so many unit flakes @odvarkadaniel ?

**Comment by odvarkadaniel** [comment]
> Do we know why we had so many unit flakes @odvarkadaniel ?

Connection lost 1x
Cannot initialize namespace 1x
Pod context cancelled 1x
Regular flake 3x
CRD now found 1x

From what I have looked into this, it seems like CI was really slow yesterday, other than that, I am sure it is not introduced by this PR as we don't change the unit tests at all here. Let me try and run the unit test a couple of more times to see what's up with it today.

**Comment by odvarkadaniel** [comment]
The significant bump of timeouts for the cluster stabilisation part can be justified due to following data:

- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-control-plane-machine-set-operator-263-periodics-e2e-aws/1721634814446014464
For this successful run on AWS, which to 3h33min, we can see that the second test in the suite (`an instance is terminated on the cloud provider should replace the outdated machine when deleted`) takes half of the time of the test running due to waiting for the cluster to stabilise after the first test (`the instance type is changed should perform a rolling update`) and then to stabilise itself, which can, due to `etcd`, take quite some time.

- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-control-plane-machine-set-operator-263-periodics-e2e-gcp/1721634792551747584
Pretty much the same thing can be said about the test suite on GCP.

Currently, the tests are passing in much better rates (14/15 on AWS, 11/15 on GCP - 2 of the failures didn't have to do anything with the newly introduced tests). We have also introduced an informer, so that ART team doesn't revert the tests so quickly. I think that will all these aforementioned points above, we can safely re-merge these tests as they are just tests anyways.

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp 5

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-azure 5

**Comment by JoelSpeed** [comment]
Looks like the linter is complaining on the go header on the new reporter thing

**Comment by odvarkadaniel** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-aws 5

**Comment by JoelSpeed** [comment]
The flake reporting isn't quite working as expected as prow is only picking up the first JUnit file. Can you try using [this merge function](https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/junit_report.go#L304-L342) after the `RunSpecs` in the test main to merge all `xml` files in the artifacts dir into a single file and see if that fixes the 1 pass, 1 fail means a flake issue please?

Thinking about how these new tests work, I think we will want to separate out the `informing` labelled jobs and run them strictly after all other jobs have passed. Could you take a look at the bash scripts and see if you can update them to exclude the informing jobs and then run them on their own?

**Comment by odvarkadaniel** [comment]
> The flake reporting isn't quite working as expected as prow is only picking up the first JUnit file. Can you try using [this merge function](https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/junit_report.go#L304-L342) after the `RunSpecs` in the test main to merge all `xml` files in the artifacts dir into a single file and see if that fixes the 1 pass, 1 fail means a flake issue please?
> 
> Thinking about how these new tests work, I think we will want to separate out the `informing` labelled jobs and run them strictly after all other jobs have passed. Could you take a look at the bash scripts and see if you can update them to exclude the informing jobs and then run them on their own?

Tried to implement the changes you suggested - not really sure if this is the right way to do. I will monitor how CI output looks.

**Comment by odvarkadaniel** [comment]
Doesn't work at all. Don't really know what to do to fix it either.

> > The flake reporting isn't quite working as expected as prow is only picking up the first JUnit file. Can you try using [this merge function](https://github.com/onsi/ginkgo/blob/3b2a2a7e74069d66b0f64922afd3426a6167dd3c/reporters/junit_report.go#L304-L342) after the `RunSpecs` in the test main to merge all `xml` files in the artifacts dir into a single file and see if that fixes the 1 pass, 1 fail means a flake issue please?
> > Thinking about how these new tests work, I think we will want to separate out the `informing` labelled jobs and run them strictly after all other jobs have passed. Could you take a look at the bash scripts and see if you can update them to exclude the informing jobs and then run them on their own?
> 
> Tried to implement the changes you suggested - not really sure if this is the right way to do. I will monitor how CI output looks.

**Comment by JoelSpeed** [comment]
/close

I will recreate this PR once it's been rebased

**Comment by theobarberbany** [comment]
@JoelSpeed 

Discussing at backlog grooming. Did this ever get recreated post rebase?

**Comment by JoelSpeed** [comment]
It did not, I never got to it, we need to look into why this was bad, probably want to re-assign it

**Pull request closed without merging**
