### PR TITLE
OCPBUGS-36469: Bump openshift/api

### PR DESCRIPTION
**Pull request by chiragkyal**
This PR

- Vendors https://github.com/openshift/api/pull/1953

/assign @JoelSpeed

### CODE REVIEW

**Comment by chiragkyal** [comment]
`ci/prow/e2e-aws-ovn-etcd-scaling`
```
scale-up: timed out waiting for CPMS to show 4 ready replicas: timed out waiting for the condition
```

Looks unrelated to the PR changes to me.

**Comment by chiragkyal** [comment]
@JoelSpeed could you please suggest what could be the reason for this test failure?

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-ovn-etcd-scaling 

I have an open bug to look at this failure, I don't think this PR is causing it or making it worse

**Pull request merged**
