### PR TITLE
Ensure cleanup retries DeleteAllOf when list still has items

### PR DESCRIPTION
**Pull request by JoelSpeed**
The cleanup tests have been failing, which suggests we need to retry the `DeleteAllOf`. I suspect it's a timing issue within the container restricted build system, because I couldn't reproduce the failure on my local system, but this might make things a little more reliable in CI at least.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/test unit

Going to run this a few times to check it is working correctly

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-serial
/override ci/prow/e2e-aws-disruptive
/override ci/prow/e2e-aws-upgrade

None of these tests are actually affected by this code

**Pull request merged**
