### PR TITLE
[release-4.14] OCPBUGS-20408: fix: e2e: add gcp custom type to test framework

### PR DESCRIPTION
**Pull request by damdo**
Manual backport of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/244 and https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/246

### CODE REVIEW

**Comment by damdo** [comment]
/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.14-periodics-e2e-gcp

**Comment by damdo** [comment]
/hold
until we get the payload job periodic result.

**Comment by JoelSpeed** [comment]
Do we have evidence from 4.15 that this is resolving the issue?

**Comment by damdo** [comment]
/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.14-periodics-e2e-gcp

**Comment by damdo** [comment]
> Do we have evidence from 4.15 that this is resolving the issue?

@JoelSpeed yes we do. In the [fix PR targeting 4.15](https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/246) I triggered a GCP E2E periodic test, like the ones we run regularly (which were failing).

The [job passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-control-plane-machine-set-operator-246-periodics-e2e-gcp/1711853638776786944) and as you can see all the machines got correctly replaced
```
[~/src/cluster-capi-operator git:(bump-capi-providers-and-k8s-1.27)] $ curl -sSL https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/openshift-cluster-control-plane-machine-set-operator-246-periodics-e2e-gcp/1711853638776786944/artifacts/e2e-gcp/gather-extra/artifacts/pods/openshift-machine-api_control-plane-machine-set-operator-5588bbc479-qlb6h_control-plane-machine-set-operator.log | grep "Machine requires an update" | grep "77937d39-a41d-4eb4-9f46-dc934ee74c28"
I1010 22:16:00.991449       1 updates.go:473]  "msg"="Machine requires an update" "controller"="controlplanemachineset" "diff"=["MachineType: e2-custom-8-24576 != e2-custom-6-16384"] "index"=1 "name"="ci-op-g8bqq9x3-e4861-rrxmd-master-1" "namespace"="openshift-machine-api" "reconcileID"="77937d39-a41d-4eb4-9f46-dc934ee74c28" "updateStrategy"="RollingUpdate"
I1010 22:16:01.006351       1 updates.go:473]  "msg"="Machine requires an update" "controller"="controlplanemachineset" "diff"=["MachineType: e2-custom-8-24576 != e2-custom-6-16384"] "index"=2 "name"="ci-op-g8bqq9x3-e4861-rrxmd-master-2" "namespace"="openshift-machine-api" "reconcileID"="77937d39-a41d-4eb4-9f46-dc934ee74c28" "updateStrategy"="RollingUpdate"
```

Going from: `e2-custom-6-16384` to `e2-custom-8-24576`.

There is yet to be an "official" [4.15 GCP periodic](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.15/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp%22%7D%5D%7D&sortField=timestamp&sort=desc) that becomes green, but the two ([1](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp/1712281535635263488),[2](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-gcp/1712210819137146880)) relevant jobs that ran after the fix, failed for unrelated reasons (install, timeout waiting for the third machine to become ready (which eventually did)).

**Comment by JoelSpeed** [comment]
/lgtm
/approved
/label backport-risk-assessed

This only affects our test code and the tests are green, no need for QE, will add the label manually

**Comment by JoelSpeed** [comment]
/hold cancel

Periodic proof in https://pr-payload-tests.ci.openshift.org/runs/ci/2f84ff90-68c7-11ee-8ba5-05873aad4f29-0

**Pull request merged**
