### PR TITLE
openstack: volumeType is now required

### PR DESCRIPTION
**Pull request by EmilienM**
- vendoring: update openshift/api, client-go and cluster-api-actuator-pkg/testutils to latest so we have the new API for `RootVolume.VolumeType`
- openstack: update tests for required `RootVolume.VolumeType`

### CODE REVIEW

**Comment by EmilienM** [comment]
/assign JoelSpeed
/cc pierreprinetti
/test unit

I want to show you the unit errors I'm having locally, I can't figure it out yet. I'm wondering if `ExtractFailureDomain` needs update to not be liberal anymore since `volumeType` is now required.

**Comment by EmilienM** [comment]
I'll leave it as draft for now until the API PR merges. Until then, the unit tests are ready and should pass now.

**Comment by EmilienM** [comment]
``` 
gather did not start for pod must-gather-l7t6s: etcdserver: leader changed
```

Not related to that PR I think.

**Comment by JoelSpeed** [comment]
This LGTM apart from the dependency on the API fork, is this good to go once that is resolved?

**Comment by EmilienM** [comment]
> This LGTM apart from the dependency on the API fork, is this good to go once that is resolved?

Yes, I need to re vendor go client once API PR has landed and update it all there.

**Comment by EmilienM** [comment]
The PR is now ready for review @JoelSpeed 
Tests passed locally for me, let's see how it works in CI.

**Comment by EmilienM** [comment]
`e2e-openstack-operator` failing on a test with `Checking that the old machine is removed`, I'll investigate what happened.

Let's give it a retry.

/test e2e-openstack-operator


Nutanix failing during IPI install:
/test e2e-nutanix-ovn

**Comment by EmilienM** [comment]
`e2e-nutanix-ovn` is not passing two times in a row with the same error during IPI install step. I suspect it's not related to this PR and the testing history doesn't have much recent data.

**Comment by EmilienM** [comment]
It's ready to be merged I think.

**Review by pierreprinetti — APPROVED** [review]
/lgtm

**Pull request merged**
