### PR TITLE
SPLAT-1280: update documentation for vSphere

### PR DESCRIPTION
**Pull request by rvanderp3**
Update documentation with details about vSphere control plane machine set implementation.

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
Thanks @rvanderp3
/approve
/lgtm

**Comment by rvanderp3** [comment]
/test unit 

unit tests are failing for a different reason every time they are run, retesting..

**Comment by rvanderp3** [comment]
/test unit

tests are oomkilling

**Comment by damdo** [comment]
Will look into it. Thanks @rvanderp3

**Pull request merged**
