### PR TITLE
OCPBUGS-8503: [release-4.12] machine's node must be ready for CPMS machine to be ready

### PR DESCRIPTION
**Pull request by damdo**
4.12 backport of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/173

### CODE REVIEW

**Comment by wking** [comment]
Do we want to `/hold` this until the #177 series makes it back to 4.12, so we can land both this change and the follow-up pivot together in 4.12.z?

**Comment by damdo** [comment]
@wking My idea is to do a single PR to backport both changes yeah

**Comment by damdo** [comment]
To combine this PR together with https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/177 and  https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/184 once they both merge.

**Comment by damdo** [comment]
Superseded by https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/193

**Pull request closed without merging**
