### PR TITLE
Migrate Azure zone away from pointer

### PR DESCRIPTION
**Pull request by JoelSpeed**
We are seeing marshalling issues because the omitempty is dropping the empty string now from the Machine provider spec when the Azure machine controller is updating it. So we need now to make sure the CPMS is updated to understand that the field is no longer a pointer, so that it stops comparing nil pointers to empty strings.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by RadekManak** [comment]
We did not land in westus in any of the runs.
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by JoelSpeed** [comment]
This one was in westus and failed still, https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-control-plane-machine-set-operator-238-ci-4.14-e2e-azure-ovn-upgrade/1695195529912258560

**Comment by RadekManak** [comment]
I see it now, I was looking at the wrong place.

**Comment by JoelSpeed** [comment]
No longer required
/close

**Pull request closed without merging**
