### PR TITLE
[release-4.12] Backport e2e/integration testing

### PR DESCRIPTION
**Pull request by damdo**
This PR backports e2e and improved integration testing to release 4.12.
Other minor backports include:
- Testing docs
- OWNER file updates

### CODE REVIEW

**Comment by damdo** [comment]
Linting will be fixed once https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/163 merges

**Comment by JoelSpeed** [comment]
Reviewing this, it only has changes to our test code within it, no product changes. IMO that means we can merge this without a bug/QE since it won't affect the product at all. It will however, allow us to start running tests against the 4.12 branch to help us when we do need to backport fixes

/approve
/lgtm
/label backport-risk-assessed

**Comment by damdo** [comment]
This test is currently broken and the etcd team is working on making it compatible with the cpms. They are happy for us to break them temporarily until they get to fix the test.

/override ci/prow/e2e-aws-ovn-etcd-scaling

**Comment by damdo** [comment]
See https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/161#issuecomment-1385930025

/override ci/prow/e2e-aws-ovn-etcd-scaling

**Pull request merged**
