### PR TITLE
manifests: Shift from run level 31 to 30

### PR DESCRIPTION
**Pull request by wking**
Looking at 4.14.0-ec.3:

```console
$ oc adm release extract --to manifests quay.io/openshift-release-dev/ocp-release:4.14.0-ec.3-x86_64
$ ls manifests/0000_31_* | sed 's/.*0000_31_\([^_]*\)_.*/\1/' | sort | uniq -c
     12 cluster-baremetal-operator
      6 control-plane-machine-set-operator
```

That gives the cluster-version operator two nodes of manifests to apply in parallel during updates into that release.  But looking at [a 4.13-to-4.14 CI run][1] in Loki with:

```
{invoker="openshift-internal-ci/periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-upgrade/1683994228855672832"} | namespace="openshift-cluster-version" |~ "baremetalhosts.metal3|clusteroperator.*baremetal|controlplanemachineset.*machine.openshift.io|clusteroperator.*control-plane-machine-set"
```

I see:

```
I0726 01:22:11.135899       1 sync_worker.go:966] Precreated resource clusteroperator "control-plane-machine-set" (256 of 865)
I0726 01:22:11.136066       1 sync_worker.go:975] Running sync for customresourcedefinition "controlplanemachinesets.machine.openshift.io" (248 of 865)
I0726 01:22:11.187486       1 sync_worker.go:966] Precreated resource clusteroperator "baremetal" (247 of 865)
I0726 01:22:11.187558       1 sync_worker.go:975] Running sync for customresourcedefinition "baremetalhosts.metal3.io" (227 of 865)
...
E0726 01:22:12.739172       1 task.go:117] error running apply for clusteroperator "control-plane-machine-set" (256 of 865): Cluster operator control-plane-machine-set is updating versions
...
E0726 01:22:13.437277       1 task.go:117] error running apply for clusteroperator "baremetal" (247 of 865): Cluster operator baremetal is updating versions
...
E0726 01:22:30.580063       1 task.go:117] error running apply for clusteroperator "control-plane-machine-set" (256 of 865): Cluster operator control-plane-machine-set is updating versions
...
I0726 01:22:31.282047       1 sync_worker.go:990] Done syncing for clusteroperator "baremetal" (247 of 865)
...
I0726 01:24:56.935811       1 sync_worker.go:990] Done syncing for clusteroperator "control-plane-machine-set" (256 of 865)
```

So during that update, the baremetal operator's manifest node took 20s to update, and the ControlPlaneMachineSet operator's manifest node took 2m45s to update.

There are already 3 existing manifest nodes at run level 30:

```
$ ls manifests/0000_30_* | sed 's/.*0000_30_\([^_]*\)_.*/\1/' | sort | uniq -c
       25 cluster-api
       21 machine-api-operator
        1 openshift-apiserver-operator
```

But cluster-api is `TechPreviewNoUpgrade`:

```console
$ grep -c TechPreviewNoUpgrade manifests/0000_30_cluster-api_*
manifests/0000_30_cluster-api_00_credentials-request.yaml:4
manifests/0000_30_cluster-api_00_namespace.yaml:1
manifests/0000_30_cluster-api_01_images.configmap.yaml:1
manifests/0000_30_cluster-api_02_crd.core-cluster-api.yaml:12
...
```

And OpenShift API server is a single OpenShiftAPIServer CRD (not sure why that's in level 30).  But still, by shifting the CPMSO to level 30, we'll be in parallel with either the machine-api node or the cluster-api node, depending on whether TechPreviewNoUpgrade is enabled.  Back to Loki and [that CI run][1]:

```
{invoker="openshift-internal-ci/periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-upgrade/1683994228855672832"} | namespace="openshift-cluster-version" |~ "clusteroperator.*machine-api"
```

includes:

```
I0726 01:18:53.041460       1 sync_worker.go:966] Precreated resource clusteroperator "machine-api" (224 of 865)"
...
E0726 01:18:57.092349       1 task.go:117] error running apply for clusteroperator "machine-api" (224 of 865): Cluster operator machine-api is updating versions
...
I0726 01:22:11.033994       1 sync_worker.go:990] Done syncing for clusteroperator "machine-api" (224 of 865)
```

So it's taking 3m18s.

So shifting a 2m45s CPMSO to level 30 shouldn't extend the length of level 30, with CPSMO and machine-api applying in parallel manifest nodes.  And it should save us 2m25s in level 31, which would still be running the baremetal operator.  And as long as the incoming CPMSO doesn't require pre-existence of anything provided by the machine-api or cluster-api, there is no downside to increasing the parallelization this way.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-upgrade/1683994228855672832

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/approve
/lgtm

**Comment by wking** [comment]
[`Horizontal pod autoscaling (scale resource: CPU) CustomResourceDefinition Should scale with a CRD targetRef` failed][1], but I'm not clear on the mechanism.  Seems unlikely to be related to this change, because if I broke something, I'd expect some of the other test-cases and jobs to fail too.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-control-plane-machine-set-operator/227/pull-ci-openshift-cluster-control-plane-machine-set-operator-main-e2e-aws-ovn/1684267836475707392

**Comment by wking** [comment]
Checking [the update run][1] in Loki:

```
{invoker="openshift-internal-ci/pull-ci-openshift-cluster-control-plane-machine-set-operator-main-e2e-aws-ovn-upgrade/1684267836496678912"} | namespace="openshift-cluster-version" |~ "clusteroperator.*machine"
```

includes:

```
I0726 19:23:15.523198       1 sync_worker.go:966] Precreated resource clusteroperator "control-plane-machine-set" (185 of 858)
I0726 19:23:15.575038       1 sync_worker.go:966] Precreated resource clusteroperator "machine-api" (234 of 858)
...
E0726 19:23:16.473987       1 task.go:117] error running apply for clusteroperator "control-plane-machine-set" (185 of 858): Cluster operator control-plane-machine-set is updating versions
...
E0726 19:23:18.576226       1 task.go:117] error running apply for clusteroperator "machine-api" (234 of 858): Cluster operator machine-api is updating versions
...
E0726 19:23:28.322059       1 task.go:117] error running apply for clusteroperator "control-plane-machine-set" (185 of 858): Cluster operator control-plane-machine-set is updating versions
...
E0726 19:23:30.378488       1 task.go:117] error running apply for clusteroperator "machine-api" (234 of 858): Cluster operator machine-api is updating versions
...
E0726 19:26:01.307268       1 task.go:117] error running apply for clusteroperator "control-plane-machine-set" (185 of 858): Cluster operator control-plane-machine-set is updating versions
...
I0726 19:26:03.307636       1 sync_worker.go:990] Done syncing for clusteroperator "machine-api" (234 of 858)
...
I0726 19:26:20.493478       1 sync_worker.go:990] Done syncing for clusteroperator "control-plane-machine-set" (185 of 858)
```

Which confirms that the `machine-api` and CPMS task nodes are reconciling in parallel now.  This run, the CPMSO took 3m5s, 20s longer than `machine-api`, but that's still saving us time vs. CPMSO running in parallel with `baremetal` (which took ~20s again, from 19:26:22 to 19:26:38).

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-control-plane-machine-set-operator/227/pull-ci-openshift-cluster-control-plane-machine-set-operator-main-e2e-aws-ovn-upgrade/1684267836496678912

**Pull request merged**
