### PR TITLE
Inject a failure domain into a dry-run created machine

### PR DESCRIPTION
**Pull request by odvarkadaniel**
We are currently encountering issues with GCP e2e failures introduced by #175. We currently can't dry-run create the machine to ensure the validity of a providerSpec due to failure domain not being in place for this machine.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
Is there any way we can add some unit test/integration test that would cover this to make sure the failure domain is added before we do the dry run create?

**Comment by odvarkadaniel** [comment]
> Is there any way we can add some unit test/integration test that would cover this to make sure the failure domain is added before we do the dry run create?

I don't think that it is necessary to add new unit tests for this as we don't add any new logic to creating the machine infos.
We know that the logic for injecting FDs already works and there are tests for that. If this logic fails, we will never get to the stuff that is added in this PR.
Other than that, the original PR for this issue has added a new integration test to check the correctness. We can also see that the GCP integration is passing now.

**Comment by JoelSpeed** [comment]
/approve
/lgtm

Ok, I'll accept that for now, but we may want to improve it in the future, I'm skeptical

**Pull request merged**
