### PR TITLE
CFE-1086: Bump openshift/api

### PR DESCRIPTION
**Pull request by chiragkyal**
This PR

- Vendors https://github.com/openshift/api/pull/1897 and bumps client-go
- reacts on client-go changes for applyconfiguration

### CODE REVIEW

**Comment by chiragkyal** [comment]
@JoelSpeed, I think we don't have to update the validation as we did for https://github.com/openshift/machine-api-operator/pull/1242

**Comment by JoelSpeed** [comment]
Somehow this PR has caused panics across the test suite, can you please look into why they're suddenly going wrong?

**Comment by chiragkyal** [comment]
/hold 
Looks like a similar PR is already approved https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/313

**Comment by chiragkyal** [comment]
API bump already landed through https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/313
/close

**Pull request closed without merging**
