### PR TITLE
[release-4.12] OCPBUGS-13943: fix double machine creation on stale cache

### PR DESCRIPTION
**Pull request by damdo**
This is a manual cherry-pick of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/208

Superseedes https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/209

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/approve
/lgtm
/label backport-risk-assessed

**Comment by damdo** [comment]
This test is currently broken and the etcd team is working on making it compatible with the cpms. 

Given the above, and the fact the operator task completed successfully, (which covers the etcd scaling mechanism through testing CPMS), I'm going to override this to continue

/override ci/prow/e2e-aws-ovn-etcd-scaling

**Pull request merged**
