### PR TITLE
OSASINFRA-3242 [vendoring] new OpenShift API for OpenStack Block Devices

### PR DESCRIPTION
**Pull request by EmilienM**
```
go get github.com/openshift/api@master
go mod tidy && go mod vendor
```

### CODE REVIEW

**Comment by EmilienM** [comment]
`e2e-openstack-operator-zone` can be ignored today. We have a CI downtime this morning.

**Comment by JoelSpeed** [comment]
@EmilienM Do you want the openstack job to pass before this merges?

**Comment by EmilienM** [comment]
@JoelSpeed no I don't care this time. We have a CI outage, I'm looking into this today and this PR isn't going to break anything for us.
Thanks

**Pull request merged**
